spring:
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    config:
        import: security/security-default.yml
    mail:
        host: smtp.gmail.com
        port: 587

server:
    shutdown: graceful
    servlet:
        session:
            cookie:
                same-site: none
                secure: true