spring:
    config:
        import: security/security-default.yml
    mail:
        host: smtp.gmail.com
        port: 587

server:
    shutdown: graceful
    servlet:
        session:
            cookie:
                same-site: none
                secure: true
decorator:
    datasource:
        p6spy:
            enable-logging: true