spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL

  jpa:
    hibernate:
      ddl-auto: create
cors:
  allow-origins: http://localhost:3000

emergency:
  email: ~