== 대여 관련 API

=== 용어 설명

- 대여 : 대여 예약 상세의 각 갯수 하나하나에 적절한 기자재 품목이 할당된 경우.
- 대여 상세(`equipmentRentalSpec`) : 대여 예약 상세의 신청 갯수 중 하나에 품목을 할당 한 것.

=== 대여 생성 API

operation::admin_createRental[snippets='http-request,http-response']

=== 특정 날짜에 대여 수령되어야 할 대여 예약들을 대여 상세와 함께 조회 API

`acceptDateTime` 과 `rentalSpecs` 가 `null` 이면 아직 수령되지 않음(즉 대여되지 않음)을 의미.

operation::admin_getReservationsWithRentalSpecsByStartDate[snippets='http-request,http-response']

=== 특정 날짜에 반납되어야 할 대여 예약과 연체된 대여 예약을 대여 상세와 함께 조회 API

`overdueReservations` 는 연체된 예약을 의미한다.
`reservationsByEndDate` 는 반납되어야 할 예정인 대여 예약을 의미한다.

operation::admin_getReservationsWithRentalSpecsByEndDate[snippets='http-request,http-response']

=== 대여 반납

==== `status` 는 반납이 어떤 상태인지 의미한다.

- `RETURNED` : 정상 반납 (만약 반납 당시가 반납일보다 늦은 경우 자동으로 연체 반납 처리됨)
- `LOST` : 분실
- `BROKEN` : 파손
- `OVERDUE_RENTED` : 연체 (연체가 시작됨을 의미.
아직 반납되지 않음)

operation::admin_returnRentals[snippets='http-request,http-response']

=== 내 대여 이력 조회

operation::getRentals[snippets='http-request,http-response']

=== 품목 사용 이력 조회

operation::admin_getReturnedRentalSpecsByPropertyNumber[snippets='http-request,http-response']