create table asset
(
    dtype           varchar(31)  not null,
    id              bigint generated by default as identity,
    max_rental_days integer      not null,
    name            varchar(255) not null,
    total_quantity  integer      not null,
    category        varchar(255),
    components      varchar(255),
    description     varchar(255),
    img_url         varchar(255),
    maker           varchar(255),
    purpose         varchar(255),
    rental_place    varchar(255),
    is_available    boolean,
    primary key (id)
);

alter table inventory
    rename column equipment_id TO asset_id;

alter table item rename column equipment_id TO asset_id;

alter table reservation_spec
    rename column equipment_id TO asset_id;

alter table asset
    add constraint UK_ASSET_NAME unique (name);

alter table item
    add constraint UK_ITEM_PROPETY_NUMBER unique (property_number);

alter table inventory
    add constraint FK_INVENTORY_ASSET foreign key (asset_id) references asset (id);

alter table reservation_spec
    add constraint FK_RESERVATION_SPEC_ASSET foreign key (asset_id) references asset (id);

alter table inventory
drop
constraint FK_INVENTORY_EQUIPMENT;

alter table reservation_spec
drop
constraint FK_RESERVATION_SPEC_EQUIPMENT;


INSERT INTO asset (dtype, id, max_rental_days, name, total_quantity, category, components, description, img_url, maker,
                   purpose, rental_place, is_available)
SELECT 'equipment',
       id,
       max_rental_days,
       model_name,
       total_quantity,
       category,
       components,
       description,
       img_url,
       maker,
       purpose,
       rental_place,
       NULL
FROM equipment;

